# These are supported funding model platforms

github: thenic # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: thenic # Replace with a single Patreon username
custom: ["https://www.buymeacoffee.com/thenic"]
